name: Build Windows x64 EXE

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Qt 6 x64
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.0
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          modules: qt5compat

      - name: Configure
        run: |
          cmake -B build -A x64 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded

      - name: Build
        run: |
          cmake --build build --config Release -j 4

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: UEFITool-Win64
          path: |
            build/UEFITool/Release/UEFITool.exe
            build/UEFIExtract/Release/UEFIExtract.exe
            build/UEFIFind/Release/UEFIFind.exe
