name: Build Windows 64bit EXE Only

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-windows-x64:
    runs-on: windows-2022
    name: Build Windows x64 EXE
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Download static Qt 6.5.0 x64
        uses: actions/checkout@v4
        with:
          repository: LongSoft/qt-6-static-x64-msvc2022
          path: qt6
          lfs: true

      - name: Unpack Qt
        shell: bash
        run: 7z x qt6/qt-6.5.0-static-x64-msvc2022.7z -o../

      - name: Create build dir
        run: mkdir build

      - name: CMake configure
        working-directory: build
        run: |
          cmake .. -G "Visual Studio 17 2022" -A x64 ^
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/../qt-6.5.0-static-x64-msvc2022" ^
          -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"

      - name: Build release
        working-directory: build
        run: cmake --build . --config Release -j4

      - name: Collect EXEs
        run: |
          mkdir dist
          copy build\UEFITool\Release\UEFITool.exe dist\
          copy build\UEFIExtract\Release\UEFIExtract.exe dist\
          copy build\UEFIFind\Release\UEFIFind.exe dist\

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UEFITool-Win64-EXE
          path: dist/*.exe